# This is a sample build configuration for Docker.
image: byjg/php:7.2-cli

# enable Docker for your repository
options:
  docker: true

pipelines:
  branches:
    master:
      - step:
          deployment: Test
          script:
            - docker login $DOCKER_REGISTRY --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
            - docker run --name mysql-container --rm -e MYSQL_ROOT_PASSWORD=mysqlp455w0rd -e TZ=America/Sao_Paulo -p 3306:3306 -d mysql:5.7
            - composer install
            - composer restdocs
            - composer migrate -- reset --yes
            - docker build -t ${DOCKER_REGISTRY}/${DOCKER_LOGIN}/repository-name:${BITBUCKET_BUILD_NUMBER} -f devops/Dockerfile .
            - docker run -e APPLICATION_ENV=dev -d --name app ${DOCKER_REGISTRY}/${DOCKER_LOGIN}/repository-name:${BITBUCKET_BUILD_NUMBER}
            - sleep 10
            - vendor/bin/phpunit
            - docker push ${DOCKER_REGISTRY}/${DOCKER_LOGIN}/repository-name:${BITBUCKET_BUILD_NUMBER}
            - docker stop mysql-container app
      - step:
          deployment: Develop
          trigger: manual
          script:
            - echo "Image - ${DOCKER_REGISTRY}/${DOCKER_LOGIN}/repository-name:${BITBUCKET_BUILD_NUMBER}"
      - step:
          deployment: Production
          trigger: manual
          script:
            - echo "Image - ${DOCKER_REGISTRY}/${DOCKER_LOGIN}/repository-name:${BITBUCKET_BUILD_NUMBER}"
