# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: byjg/php:7.2-cli

# enable Docker for your repository
options:
  docker: true

pipelines:
  tags:
    v*:
      - step:
          caches:
            - node
            - composer
          script:
            # Build the Dev environment and run the tests
            - docker run --name mysql-container --rm -e MYSQL_ROOT_PASSWORD=password -e TZ=America/Sao_Paulo -p 3306:3306 -d mysql:5.7
            - composer install
            - APPLICATION_ENV=dev composer build
            - docker exec resttemplate-dev-instance composer restdocs
            - docker exec resttemplate-dev-instance composer migrate -- reset --yes
            - docker exec resttemplate-dev-instance vendor/bin/phpunit
            - docker stop resttemplate-dev-instance mysql-container

            # Deploy to live
            - APPLICATION_ENV=live composer build
    rc*:
      - step:
          caches:
            - composer
          script:
            # Just build an image.
            - composer install
            - APPLICATION_ENV=homolog composer build
